kind: pipeline
type: docker
name: integration
 
steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - exit 0
      - dotnet sonarscanner begin
          /k:"easv-devops_CDWeatherExample_AY4d5zUxEVvRW2O60EXK"
          /d:sonar.host.url="http://sonar.setgo.dk:9000"  
          /d:sonar.token="$SONARSECRET"
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

---

kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:
  - name: publish api
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: src
      dockerfile: src/WeatherAPI/Dockerfile
      repo: boulundeasv/cd-weather-api
      tags: 
        - staging

  - name: publish web
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: src
      dockerfile: src/WeatherFrontend/Dockerfile
      repo: boulundeasv/cd-weather-web
      tags: 
        - staging

  - name: trigger update
    image: alpine
    commands:
      - curl -X GET "http://84.247.167.129:8080/v1/update" -H "Authorization: Bearer mytoken" # Must match the token defined in docker-compose.yml
    depends_on:
      - publish api
      - publish web
